<?php

namespace BFOS\PagseguroBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PedidoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PagamentoRepository extends EntityRepository
{
    public function persist(Pagamento $pagamento){
        $this->_em->persist($pagamento);
    }

    public function flush(){
        $this->_em->flush();
    }
}