<?php

namespace BFOS\PagseguroBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TransacaoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransacaoRepository extends EntityRepository
{
}